### ISSUE TITLE
smart-on-fhir/api-server ./grailsw run-script scripts/LoadCCDA.groovy run-script: command not found

### ISSUE THREAD

**Issue by ascooper57** [smart-on-fhir/api-server#36]
Storing Documents + DocumentReferences

BASE_URL="http://localhost:8080" \
CLIENT_ID=client \
CLIENT_SECRET=secret \
PATIENT_ID="1234" \
CCDA="grails-app/conf/examples/ccda.xml"\
./grailsw run-script scripts/LoadCCDA.groovy
ERROR: -bash: run-script: command not found

ERROR: file does not exist grails-app/conf/examples/ccda.xml

**Comment by jmandel** [comment]
I'm inclines to remove this C-CDA loader, given that it was first written to support the Blue Button REST API (no longer under development). @ascooper57 do you have a use case for this, or are you just concerned that it's broken?

**Comment by ascooper57** [comment]
I am trying to "contribute" to the quality and integrity of your project in any meaningful way. I encountered a set of instructions that did not work as documented, so I reported it as an act of respect for your efforts.
We are trying to acquire as many C-CDA patient profiles and observations as we can since we are in the data analytics business. Access to more sources of data via REST APIs is of value to our efforts. An interface into Blue Button's data potentially expands our Total Available Market and data sets.

**Comment by jmandel** [comment]
We definitely appreciate your feedback here! Consistent, working docs are
key for our success.

I just noticed that this particular functionality may no longer be
relevant, since it was specifically tied to a now-defunct attempt at
defining a Blue Button REST API. It's important for you to know that work
in this direction is still going on, but with a stronger focus on
structured, granular data rather than C-CDA. Given that we're a small team,
there's only so much we can focus on. So I think the right fix for this
particular documentation bug is actually to remove this feature from the
release (and remove the corresponding documentation). Again, thank you for
bringing it up -- we really appreciate it!

Note that we'll likely re-introduce a similar feature in the near future as
we work with the Argonaut Implementation community on a series of
free-to-join "sprints" that you may be interested in:
http://argonautproject.org/

**Comment by ascooper57** [comment]
I understand now and agree with you that the instructions should be removed
from the documentation.

Alan S. Cooper
<http://www.linkedin.com/in/ascooper1>

**Comment by jmandel** [comment]
Great -- completed in https://github.com/smart-on-fhir/api-server/commit/3470a605aab0682cccc28522fa9d8ee6e3913322
